### ISSUE TITLE
Not all defined media players are displayed properly

### ISSUE THREAD

**Issue by kajmaj** [punxaphil/maxi-media-player#108]
**Checklist:**

- [x] I updated to the latest version available (1.10.1)
- [x] I cleared the cache of my browser

**Release with the issue: ˇˇ 1.10.1

**Last working release (if known):** 1.7.2

**Browser and Operating System: Chrome/ Win 11

I use Lyrion adon (LMS) with squeezeesp32 players. Only some are identified and displayed properly, rest of them are displayed like 'none-none' and it is not possible to control them (join/unjoin, play etc.)
There is no difference if used entities or entityPlatform: squeezebox

![Snímek obrazovky 2024-10-13 140403](https://github.com/user-attachments/assets/4fcf02c1-89f9-44d5-b0b2-092fe3aeb755)
![Snímek obrazovky 2024-10-13 140455](https://github.com/user-attachments/assets/3a268354-9c6c-4177-a6a6-b224045f38b5)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

media card definition:

  type: custom:maxi-media-player
  excludeItemsInEntitiesList: false
  entityPlatform: squeezebox
  widthPercentage: auto
  heightPercentage: auto
  hideBrowseMediaButton: true
  volumeStepSize: 2 
  adjustVolumeRelativeToMainPlayer: true
  dynamicVolumeSlider: false
  hideVolumeCogwheel: true

**Comment by punxaphil** [comment]
As I don't have such devices I need some more information. Please go to Developer Tools -> States (/developer-tools/state)
Find your media devices and share all attributes listed.
Also, for the join part. I can't see in the integration that it supports grouping. Are you sure it does?
https://www.home-assistant.io/integrations/squeezebox/

**Comment by kajmaj** [comment]
All attributes of one 'grouped' media players:

group_members: media_player.obyvak, media_player.pracovna, media_player.garaz 
volume_level: 0.21 
is_volume_muted: false 
media_duration: 0 
media_position: 0 
media_position_updated_at: 2024-10-13T18:12:35.092232+00:00 
media_title: None 
media_artist: None 
media_album_name: None 
media_channel: None 
shuffle: true 
repeat: off 
query_result:  {}  
entity_picture: /api/media_player_proxy/media_player.garaz?token=849d81d8fbc8d2b84277d3e0c13aac7d0f3c7722b6099562f7dc9165ab3c576c&cache=0e9c26439fbac0f5 
icon: mdi:speaker-wireless 
friendly_name: Garáž
supported_features: 3077055

Regarding grouping: It works. As you can see, three players are grouped, able to play together.

Update:
 when I downgraded to 1.7.2 and then upgraded back to 1.10.1 it behaves as expected.

**Comment by punxaphil** [comment]
So everything is fine now?

**Comment by kajmaj** [comment]
Yes. It is. Thank you.
