### ISSUE TITLE
Volume controls not working with plex

### ISSUE THREAD

**Issue by chicco-carone** [punxaphil/maxi-media-player#120]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**  v1.14.1

**Last working release (if known):** Unknown

**Browser and Operating System:** Arch linux/Zen browser (also tested on chrome and firefox and android with the official client)

**Description of problem:**
The volume for clients using the plex integration isn't working. Its always set to 100% and if you try to change it it doesn't apply and goes back to 100%. It doesn't give any issues in the js console apart from player unavailble since not all players in the plexamp integrations are always avaiable.
![Screenshot_20241108_103825](https://github.com/user-attachments/assets/1da37fdc-3dd4-4fb7-9711-890fc5027c5e)
I don't have any other media players to test it so i can't be sure if its an issue specifically with the plexamp integration or the card itself

The volume should be connected the player's one 

**Javascript errors shown in the web inspector (if applicable):**
No errors

**Additional information:**

**Comment by punxaphil** [comment]
Does it work in the built in home assistant media player?

**Comment by chicco-carone** [comment]
I was going to try with homeassistant player but i noticed that it fixed itself and it's now working fine.
![Screenshot_20241108_205515](https://github.com/user-attachments/assets/b5e02a6f-7242-40ff-bebb-842291578d81).
After deleting the queue and leaving the player without anything in the queue it had the same issue. Also using other media player integrations such as mini media player the volume works also when there isn't anything in the queue and nothing is playing

**Comment by realhagie** [comment]
Same Problem here, Volume Controls are not working anymore , slider, vol+/- and mute not working. Other players like HA or mini-media working. Other Controls like start/stop / power are still working. 
I downgraded to < 1.4.0 still not working. Must be some change from HA which broke the controls.
Nothing the log either.

**Comment by punxaphil** [comment]
https://github.com/punxaphil/maxi-media-player/releases/tag/v1.14.2

---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Comment by realhagie** [comment]
Sorry but this Problem still peresist.  I deleted and redownloaded the latest Version. I cleared the cache. 

![Recording 2024-11-15 at 10 27 54](https://github.com/user-attachments/assets/6d6be76f-f2cc-4d7d-a62e-5eeac3230cf0)

**Comment by punxaphil** [comment]
You are using Plex integration?

**Comment by chicco-carone** [comment]
The issue persists on my end too with the plex intergration

**Comment by realhagie** [comment]
> You are using Plex integration?

no Music Assistant.

**Comment by punxaphil** [comment]
No worries.
So what kind of device through music assistant?

**Comment by realhagie** [comment]
It's slimproto (squeezebox player) I use the addon to play music using a local usb soundcrad. https://github.com/pssc/ha-addon-squeezelite this is the addon.  Controls were working some weeks ago.
