### ISSUE TITLE
<Integration punxaphil/maxi-media-player> Repository structure for v1.14.2 is not compliant

### ISSUE THREAD

**Issue by Jafesu** [punxaphil/maxi-media-player#125]
**Checklist:**

- [X ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
Latest

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
When I add the repo to have I get the following error, and unable to install the integration 

<Integration punxaphil/maxi-media-player> Repository structure for v1.14.2 is not compliant

![Screenshot_20241117_081630_Home Assistant.jpg](https://github.com/user-attachments/assets/8dae276d-fe7e-459b-9cee-245c5ea8f7ee)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by punxaphil** [comment]
You need to select "plugin" (not "integration")
