### ISSUE TITLE
Volume Section don't show Entities

### ISSUE THREAD

**Issue by realhagie** [punxaphil/maxi-media-player#133]
I added 3 entities to the card, "Bistro" "Xiaomi Speaker" and a Univesal Media Player Group which is build in Music Assistant. This Group is for players which cannot usually grouped just to play the same music without the need to have them synced 100%. I can control every Entity by switching to it. But they are not listed in the Volumes Section Overview.

![Recording 2024-12-02 at 12 32 18](https://github.com/user-attachments/assets/d56229b8-d289-40b1-90f8-9b467fbdd667)

Maybe I have a misunderstanding with this section or fixing the problem lead to another ?

**Comment by punxaphil** [comment]
Yes, that is a misunderstanding. The volumes will only show the currently selected player (including its group members)
