### ISSUE TITLE
Add Stop Option

### ISSUE THREAD

**Issue by cnewman402** [punxaphil/maxi-media-player#138]
**Is your feature request related to a problem? Please describe.**
I cannot stop the music. HEOS/Denon does not support Pause.

**Describe the solution you'd like**
A solution could be similar to mini-media-player which has replace_mute: stop

**Describe alternatives you've considered**
My only other option is to add another player to stop or open my phone. I could do voice control via Google, but I have all my mics closed on voice control.

**Additional context**
Nothing further. Great solution. I cannot find anything better. I spent a few hours getting XM into it tonight. Having XM tiles/favorites has been a want of mine for years. If I had any other wishes on this card it would be move some of the tabs just into home, i.e. favorite under the volume bar in the Home tab. Thank you for your consideration in advance.

**Comment by punxaphil** [comment]
https://github.com/punxaphil/maxi-media-player/releases/tag/v1.16.0
`stopInsteadOfPause: true`

---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
