### ISSUE TITLE
Possibility to exclude all favorites except custom favorites

### ISSUE THREAD

**Issue by Strixx76** [punxaphil/maxi-media-player#144]
**Is your feature request related to a problem? Please describe.**
Not to your card but if you have for example the [Radio Browser integration](https://www.home-assistant.io/integrations/radio_browser/) installed ti will clutter the favorites tab and show all root item from radio browser.

**Describe the solution you'd like**
A simple setting to only show custom favorites, or excluding/including all media from certain domains.

**Describe alternatives you've considered**
Can't think of any.

**Comment by punxaphil** [comment]
https://github.com/punxaphil/maxi-media-player/releases/tag/v8.5.0
Use `favoritesToIgnore`.
Example:
```
favoritesToIgnore: # will compare both against title and media_content_id
  - My Favorite Album # Hide specific title
  - Christmas # Hide any titles matching 'Christmas'
  - radio_browser # Hide any radio stations from radio_browser (since their media_content_id contains this string)
```
