### ISSUE TITLE
Easier setup of card

### ISSUE THREAD

**Issue by Strixx76** [punxaphil/maxi-media-player#145]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Move the "Entity Platform" from "Advanced"-tab to "General"-tab, and perhaps have a drop down of all platforms that provides media_players.

**Describe alternatives you've considered**
None

**Additional context**
I was very close to giving up trying this fantastic card because it sad “No supported players found”. So I thought it only supported Sonos speakers. Finally I found the setting so that I could add all my multi room speakers.

**Comment by punxaphil** [comment]
https://github.com/punxaphil/maxi-media-player/releases/tag/v8.4.0
* New info text: "No players found. Make sure you have configured entities in the card's configuration, or configured `entityPlatform`."
* Moved entityPlatform to entities section


---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
