### ISSUE TITLE
Display the source in the player for Bose

### ISSUE THREAD

**Issue by cyrilthomas** [punxaphil/maxi-media-player#34]
**Is your feature request related to a problem? Please describe.**
View the current source playing on Bose soundtouch

**Describe the solution you'd like**
Along side the title display on the player show the source - airplay, tunein, Bluetooth, aux, hdmi etc..

**Describe alternatives you've considered**
Currently need a separate media player entry card to display this info

**Additional context**

**Comment by punxaphil** [comment]
Is it showing in the volumes section?

**Comment by cyrilthomas** [comment]
Not sure if I got your question correctly. But the volumes section only allows choosing a source. I was more interested to see which source from the bose source is playing. The default media player shows this as **product** when playing via hdmi, spotify when playing wirelessly via spotify app or tunein when playing a bose preset radio. I couldn’t find a way to see this information anywhere within this media player view.

**Comment by punxaphil** [comment]
Ok, but why did you close the issue?

**Comment by cyrilthomas** [comment]
I didn’t mean to. Might have accidentally chosen code issue with my comment

**Comment by punxaphil** [comment]
Please try: https://github.com/punxaphil/maxi-media-player/releases/tag/v1.7.1
`showSourceInPlayer: true`

**Comment by cyrilthomas** [comment]
Thank you! Works now.
