### ISSUE TITLE
Google cast media players not showing up

### ISSUE THREAD

**Issue by dnestico** [punxaphil/maxi-media-player#4]
**Checklist:**

- [ Yes] I updated to the latest version available
- [Yes ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Arc Browser aka Chromium

**Description of problem:**

I selected the "Cast" platform aka Google Cast and the media players aren't showing up, I even tried adding them individually and still nothing.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

Code:

```
type: custom:maxi-media-player
sections:
  - player
  - volumes
  - groups
  - grouping
  - media browser
showVolumeUpAndDownButtons: false
entities: []
topFavorites:
  - ''
entityPlatform: cast
artworkAsBackground: true
```
<img width="519" alt="Screenshot 2024-03-22 at 3 54 55 PM" src="https://github.com/punxaphil/maxi-media-player/assets/3034555/df4367f6-9494-4625-b354-77a61e37582c">

**Comment by punxaphil** [comment]
Can you try this new release?
# [ v1.2.0](https://github.com/punxaphil/maxi-media-player/tree/v1.2.0)

## 🐛 Fixes

* [fix: missing name for players that don't support grouping](https://github.com/punxaphil/maxi-media-player/commit/ea57ab389845e92049b9d38ce5c5589ff596c9f9)
* [fix: log warning if player is not available](https://github.com/punxaphil/maxi-media-player/commit/128433c5e8e73da03816a544c21001ff4966a769)

**Comment by dnestico** [comment]
It seems to be working on a different browser aka Safari but still looks the same on Arc Browser, I've cleared and disabled the cache a million times so not sure how to fix it at this point tbh.

**Comment by dnestico** [comment]
Looks like a reinstall fixed it on my browser! Thanks.

**Comment by punxaphil** [comment]
That looks strange, please share your card config.
It should look like this:
<img width="502" alt="image" src="https://github.com/punxaphil/maxi-media-player/assets/26582898/1f1481c0-b052-4965-a5a6-114d67799e19">

**Comment by dnestico** [comment]
That was before I figured out how to add media now I added the radio browser, soon will add youtube music.

Btw it seems that folders don't work in the card, would be a good update, and also would be nice if we could add media sources via the UI instead of YAML.

<img width="541" alt="Screenshot 2024-04-01 at 5 08 04 PM" src="https://github.com/punxaphil/maxi-media-player/assets/3034555/b9e33797-99ef-4699-a00b-0b4470258d4f">


```
type: custom:maxi-media-player
sections:
  - player
  - volumes
  - media browser
  - groups
entities: []
favoritesToIgnore:
  - Cloud
  - Google
  - Driveway
  - Driveway Person
  - Driveway Car
  - Garage
  - Garage Person
  - Garage Car
  - Garage Dog
  - Front door doorbell Recent Events
  - Google en com
  - Home Assistant Cloud
  - PetFeeder
  - Porch
  - Porch Person
  - Porch Dog
  - Vaughan Radar
  - usb
  - floppy
  - By Language
  - By Category
  - cdrom
  - Popular
  - Clips [192.168.2.176:5000]
  - Snapshots [192.168.2.176:5000]
  - Recordings [192.168.2.176:5000]
topFavorites:
  - Radio Browser
entityPlatform: cast
showVolumeUpAndDownButtons: false
dynamicVolumeSlider: true
hideBrowseMediaButton: false
mediaBrowserTitle: Media Browser
mediaBrowserItemsPerRow: 5
artworkAsBackground: true
showAudioInputFormat: true

```

**Comment by punxaphil** [comment]
I’m afraid you’ve misunderstood it. That section only supports favourites. Nothing else. The rest of the media can only be found through the “browse media” button.

**Comment by kajmaj** [comment]
Is there any way how to config "own" favorites? Sthg like radio presets?
