### ISSUE TITLE
Homepod

### ISSUE THREAD

**Issue by thebadboyltz** [punxaphil/maxi-media-player#58]
Hello, I’m using your code and it’s great. However there is a problem with my HOMEPOD, when it is paused there is no option to restart playback like on the original card. In my screenshot you can see the play function circled in red. How can I add it? THANKS

![IMG_9777](https://github.com/punxaphil/maxi-media-player/assets/153684851/fc81759e-f907-4bc8-ace3-9687faf4266c)
![IMG_9778](https://github.com/punxaphil/maxi-media-player/assets/153684851/f4e7f1a8-dfd7-4913-90c1-7f2106a405cc)

**Comment by punxaphil** [comment]
Thanks for this suggestion. I'll look into it.

**Comment by jtonk** [comment]
Would be great to get this fixed. I have a couple of shairplay players, linked through music assistant and I have the same or similar issue.

**Comment by punxaphil** [comment]
Try this one https://github.com/punxaphil/maxi-media-player/releases/tag/v1.7.2

---
PunxaPhil
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
