### ISSUE TITLE
Support Snapcast Groups

### ISSUE THREAD

**Issue by alex-phillips** [punxaphil/maxi-media-player#66]
**Is your feature request related to a problem? Please describe.**
My media players are using the snapcast integration. So far everything is working as expected with the exception of grouping. It appears that snapcast doesn't use the default `media_player.join/unjoin` service, but instead uses `snapcast.join/unjoin`. 

**Describe the solution you'd like**
Would be great if there was a configuration option to allow for some integration-specific changes such as snapcast's join services.

**Comment by punxaphil** [comment]
Honestly, it makes no sense for snapcast to not support the standard media_player.join/unjoin. Please ask the snapcast integration implementer to support it.
That's how the Sonos integration did it. Before they had their own join/unjoin. Now they simply support the media_player one.
