### ISSUE TITLE
Blur album art or dynamic colour based controls from album colours, like android auto

### ISSUE THREAD

**Issue by andiohn** [punxaphil/maxi-media-player#85]
Dynamic colour for controls based on android auto.
Blur level on album art too

**Comment by punxaphil** [comment]
Dynamic colour I'm not sure how to do. Would need someone contributing to the repo for that.

For blur, use cardmod (https://github.com/thomasloven/lovelace-card-mod):
```
type: custom:maxi-media-player
card_mod:
  style:
    mxmp-player$: |
      .artwork {        
        filter: blur(2px);
      }
```
