### ISSUE TITLE
Where are Favorites originating from?

### ISSUE THREAD

**Issue by mllockwood** [punxaphil/maxi-media-player#87]
I use Music Assistant with Spotify.  My Spotify "Favorites" are not pulling in to the card.  Am I missing something in the config, or do Favorites not work with Spotify?

**Comment by punxaphil** [comment]
It is looking for favorites in two places:
* media_player/browse_media with content_id=favorites 
  * Link to Home Assistant docs: https://developers.home-assistant.io/docs/core/entity/media-player/#browse-media)
  * Link to where it's used in the card: https://github.com/punxaphil/maxi-media-player/blob/main/src/services/media-browse-service.ts#L36
* on the attribute "source_list" on the player entity
  * Link to where it's used in the card: https://github.com/punxaphil/maxi-media-player/blob/main/src/services/media-browse-service.ts#L49
