### ISSUE TITLE
Playback control buttons disappear when the track is paused

### ISSUE THREAD

**Issue by realroywalker** [punxaphil/maxi-media-player#95]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 1.7.1

**Last working release (if known):** N/A

**Browser and Operating System:** Chrome - Windows 11

**Description of problem:** When pausing a track the play/pause and next / prev track buttons all disappear and the artwork grows to fill the space.. since the buttons disappear I can't then resume the track - is it supposed to behave this way?

**Additional information:** YAML I'm using;
```
type: custom:maxi-media-player
sections:
  - player
  - media browser
entities:
  - media_player.lenovo_starview
showVolumeUpAndDownButtons: false
hidePlayerControlRepeatButton: true
hidePlayerControlShuffleButton: true
dynamicVolumeSlider: false
hideBrowseMediaButton: false
artworkAsBackground: false
showSourceInPlayer: false
hidePlayerControlPowerButton: false
```

**Comment by punxaphil** [comment]
Try this one: https://github.com/punxaphil/maxi-media-player/releases/tag/v1.7.2
---
PunxaPhil
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Comment by realroywalker** [comment]
> Try this one: https://github.com/punxaphil/maxi-media-player/releases/tag/v1.7.2
> 
> PunxaPhil [![image](https://private-user-images.githubusercontent.com/26582898/282265260-9bebc1f6-6bda-4cbd-b596-50d3d2f712de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMTk4NjUsIm5iZiI6MTcyNzExOTU2NSwicGF0aCI6Ii8yNjU4Mjg5OC8yODIyNjUyNjAtOWJlYmMxZjYtNmJkYS00Y2JkLWI1OTYtNTBkM2QyZjcxMmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE5MjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZTExZjk3MzgzYWMwNGIzNGI1ZGNlMmFjZWE1NmJmNDA4MGVkODQ1YWZmN2I5OTg0OTgxNWZjNTQ1MDRjMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J032H9zwl7eqIIQQiArhOvUEVW6mDJ7AlSAW2xEjOW0)](https://www.buymeacoffee.com/punxaphil)

Works perfectly - many thanks! 👍
